- name: be sure ntp is installed
  apt: pkg=ntp state=installed

- name: be sure ntp is configured
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntpd

- name: be sure ntpd is running and enabled
  service: name=ntp state=running enabled=yes